import { Link } from "react-router-dom";

const methodologyUrl = "https://www.thepartneringgroup.com/tpg-persuasive-storytelling/";

const tools = [
  {
    name: "StoryLab",
    headline: "Build and evaluate your story",
    copy: "Upload your deck. Get a story read. Fix a section. Build from scratch.",
    badge: "Free entry + Paid",
    badgeTone: "free",
    cta: "Try StoryLab",
    to: "/storylab"
  },
  {
    name: "Ask the Coach",
    headline: "Get coached on your story",
    copy: "AI coaching on the TPG methodology, from Proper Prep to story arcs and delivery.",
    badge: "Lite + Paid",
    badgeTone: "paid",
    cta: "Go to Ask the Coach",
    to: "/coach"
  },
  {
    name: "Own the Room",
    headline: "Master your delivery",
    copy: "Record a run-through. Get timestamped feedback on pace, presence, and body language.",
    badge: "Paid",
    badgeTone: "paid",
    cta: "Go to Own the Room",
    to: "/delivery"
  }
];

const proofPoints = [
  {
    value: "$1M+",
    label: "Incremental sales generated by one global client within six months of training"
  },
  {
    value: "46%",
    label: "Top-line sales lift achieved by a client following program completion"
  },
  {
    value: "4.8/5",
    label: "Average participant rating across TPG storytelling programs globally"
  }
];

const testimonials = [
  {
    quote:
      "The most practical commercial training I've been through in 15 years. I used the framework in a top-to-top the following week and walked out with a yes.",
    person: "National Account Manager",
    company: "Global CPG Company"
  },
  {
    quote:
      "They teach persuasion. My team now builds every deck with the What / So What / Now What framework and our win rate has measurably improved.",
    person: "Head of Commercial Capabilities",
    company: "B2B Industrial Manufacturer"
  },
  {
    quote:
      "I've sat through a lot of storytelling training. This is the only one where I changed how I actually work the next day. The Opening Gambit alone is worth the price.",
    person: "Senior Director, Category Leadership",
    company: "Leading Beverage Manufacturer"
  }
];

export default function PublicHomePage() {
  return (
    <div className="public-page">
      <section className="public-hero public-hero-home">
        <div className="public-section-inner public-hero-centered">
          <p className="public-kicker">Deckspert by TPG</p>
          <h1>The TPG methodology. Now interactive.</h1>
          <p className="public-hero-copy">
            Build, evaluate, and deliver presentations that get more yeses, more often.
          </p>
          <div className="public-action-row public-action-row-centered">
            <Link className="public-primary-button" to="/storylab">
              Try the Free Evaluator
            </Link>
            <Link className="public-outline-button public-outline-button-dark" to="/coach">
              Talk to the Coach
            </Link>
            <Link className="public-text-link-dark" to="/platform">
              Log In
            </Link>
          </div>
        </div>
      </section>

      <section className="public-section">
        <div className="public-section-inner">
          <p className="public-kicker public-kicker-blue">Three tools. One methodology.</p>
          <h2>Everything you need to build, refine, and deliver a better story.</h2>
          <p className="public-intro">
            Deckspert turns TPG Persuasive Storytelling into an always-on platform for real presentations, real teams,
            and real commercial moments.
          </p>
          <div className="tool-card-grid">
            {tools.map((tool) => (
              <article className="tool-card" key={tool.name}>
                <span className={`tool-badge tool-badge-${tool.badgeTone}`}>{tool.badge}</span>
                <h3>{tool.name}</h3>
                <strong>{tool.headline}</strong>
                <p>{tool.copy}</p>
                <Link to={tool.to}>{tool.cta}</Link>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="public-section public-section-light">
        <div className="public-section-inner public-centered-copy">
          <p className="public-kicker public-kicker-blue">Built on the TPG methodology</p>
          <h2>Deckspert is not another AI tool. It is the training, made interactive.</h2>
          <p className="public-intro">
            These tools are built on the TPG Persuasive Storytelling methodology. Five frameworks. Used in training
            programs across 17 countries. Deckspert puts them in your hands between presentations.
          </p>
          <p className="public-intro public-intro-tight">
            If you have not been through the training, start with the free tools. Then book a conversation.
          </p>
          <div className="public-action-row public-action-row-centered">
            <a className="public-outline-button" href={methodologyUrl}>
              Learn about the training programs
            </a>
          </div>
        </div>
      </section>

      <section className="public-section public-section-dark">
        <div className="public-section-inner">
          <p className="public-kicker">Results</p>
          <h2>Teams that present better close more.</h2>
          <div className="public-stat-row">
            {proofPoints.map((point) => (
              <div className="public-stat-card" key={point.value}>
                <strong>{point.value}</strong>
                <span>{point.label}</span>
              </div>
            ))}
          </div>
          <div className="public-quote-grid">
            {testimonials.map((item) => (
              <figure className="public-quote-card public-quote-card-dark" key={item.person}>
                <blockquote>{item.quote}</blockquote>
                <figcaption>
                  <strong>{item.person}</strong>
                  <span>{item.company}</span>
                  <em>Outcome from TPG storytelling training</em>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      <section className="public-section public-section-dark public-final-cta">
        <div className="public-section-inner public-centered-copy">
          <h2>Ready to get more yeses, more often?</h2>
          <p className="public-intro">
            Start with the free tools. Or book a conversation. Either way, you will see the difference.
          </p>
          <div className="public-action-row public-action-row-centered">
            <a className="public-primary-button" href="https://calendly.com/tbradley-tpg-mail/storytelling-30-min-conversation">
              Book a discovery call
            </a>
            <Link className="public-outline-button public-outline-button-dark" to="/pricing">
              Explore pricing
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
