import { Link } from "react-router-dom";

const methodologyUrl = "https://www.thepartneringgroup.com/tpg-persuasive-storytelling/";
const CALENDLY = "https://calendly.com/tbradley-tpg-mail/storytelling-30-min-conversation";

const stripStats = [
  { value: "22x", label: "More memorable" },
  { value: "17", label: "Countries" },
  { value: "4.8/5", label: "Participant rating" },
  { value: "$1M+", label: "Sales impact" }
];

const proofPoints = [
  {
    value: "22x",
    label: "More memorable — stories told in the TPG framework are retained far longer than data-led presentations"
  },
  {
    value: "17",
    label: "Countries where TPG Persuasive Storytelling programs have been delivered"
  },
  {
    value: "$1M+",
    label: "Incremental sales generated by one global client within six months of training"
  },
  {
    value: "46%",
    label: "Top-line sales lift achieved by a client following program completion"
  },
  {
    value: "4.8/5",
    label: "Average participant rating across TPG storytelling programs globally"
  }
];

const testimonials = [
  {
    quote:
      "The most practical commercial training I've been through in 15 years. I used the framework in a top-to-top the following week and walked out with a yes.",
    person: "National Account Manager",
    company: "Global CPG Company"
  },
  {
    quote:
      "They teach persuasion. My team now builds every deck with the What / So What / Now What framework and our win rate has measurably improved.",
    person: "Head of Commercial Capabilities",
    company: "B2B Industrial Manufacturer"
  },
  {
    quote:
      "I've sat through a lot of storytelling training. This is the only one where I changed how I actually work the next day. The Opening Gambit alone is worth the price.",
    person: "Senior Director, Category Leadership",
    company: "Leading Beverage Manufacturer"
  }
];

export default function PublicHomePage() {
  return (
    <div className="public-page">

      {/* ── Hero ──────────────────────────────────────────────────────── */}
      <section className="public-hero public-hero-home">
        <div className="public-section-inner public-hero-centered">
          <p className="public-kicker">Deckspert by TPG</p>
          <h1>The TPG methodology. Now interactive.</h1>
          <p className="public-hero-copy">
            Build, evaluate, and deliver presentations that get more yeses, more often.
          </p>
          <p className="public-hero-value-line">
            Get your presentation scored in seconds. Detailed feedback sent to your email.
          </p>
          <div className="public-action-row public-action-row-centered">
            <Link className="public-primary-button" to="/free-evaluator">
              Try the Free Evaluator
            </Link>
            <Link className="public-outline-button public-outline-button-dark" to="/coach">
              Talk to the Coach
            </Link>
            <Link className="public-text-link-dark" to="/platform">
              Log In
            </Link>
          </div>
        </div>
      </section>

      {/* ── Stats strip ───────────────────────────────────────────────── */}
      <section className="public-stat-strip" aria-label="Key stats">
        <div className="public-stat-strip-inner">
          {stripStats.map((stat) => (
            <div className="public-stat-strip-item" key={stat.value}>
              <strong>{stat.value}</strong>
              <span>{stat.label}</span>
            </div>
          ))}
        </div>
      </section>

      {/* ── 3 ways section ────────────────────────────────────────────── */}
      <section className="public-section">
        <div className="public-section-inner">
          <p className="public-kicker public-kicker-blue">Start improving today</p>
          <h2>3 ways to improve your presentation.</h2>
          <p className="public-intro">
            Start with a free evaluation. Then unlock coaching, refinement, and delivery practice
            as your needs grow.
          </p>
          <div className="tool-card-grid">

            {/* Card 1 — Free Evaluator (primary free entry point) */}
            <article className="tool-card tool-card-featured">
              <span className="tool-badge tool-badge-free">Free</span>
              <h3>Evaluate your story</h3>
              <strong>Get your deck scored against the TPG framework</strong>
              <p>
                Upload your presentation and get section-level scores, key gaps, and high-level
                feedback — instantly. Full detailed analysis delivered to your email.
              </p>
              <Link className="public-primary-button tool-card-cta" to="/free-evaluator">
                Try the Free Evaluator
              </Link>
            </article>

            {/* Card 2 — Coach (free lite + paid) */}
            <article className="tool-card">
              <span className="tool-badge tool-badge-free">Free lite</span>
              <h3>Ask the Coach</h3>
              <strong>Get coached on your story</strong>
              <p>
                AI coaching on the TPG methodology — story structure, opening gambits, WIIFM,
                and close. Try a 4-minute session free.
              </p>
              <Link className="tool-card-link" to="/coach">
                Go to Ask the Coach →
              </Link>
            </article>

            {/* Card 3 — Own the Room (paid only — not a link) */}
            <article className="tool-card tool-card-locked">
              <span className="tool-badge tool-badge-paid">Paid</span>
              <h3>Own the Room</h3>
              <strong>Master your delivery</strong>
              <p>
                Record a run-through. Get timestamped feedback on pace, presence, and body
                language — powered by the TPG Dynamic Delivery framework.
              </p>
              <Link className="tool-card-unlock-link" to="/pricing">
                Unlock with full access →
              </Link>
            </article>

          </div>
        </div>
      </section>

      {/* ── Mid-page evaluator CTA ────────────────────────────────────── */}
      <section className="public-section public-section-light public-mid-cta">
        <div className="public-section-inner public-centered-copy">
          <p className="public-kicker public-kicker-blue">No account required</p>
          <h2>See where your story stands in seconds.</h2>
          <p className="public-intro">
            Upload your deck. Get scored on structure, Proper Prep, opening gambits, WIIFM, and
            close. Detailed results land in your inbox.
          </p>
          <div className="public-action-row public-action-row-centered">
            <Link className="public-primary-button" to="/free-evaluator">
              Try the Free Evaluator
            </Link>
          </div>
        </div>
      </section>

      {/* ── Methodology ───────────────────────────────────────────────── */}
      <section className="public-section">
        <div className="public-section-inner public-centered-copy">
          <p className="public-kicker public-kicker-blue">Built on the TPG methodology</p>
          <h2>Deckspert is not another AI tool. It is the training, made interactive.</h2>
          <p className="public-intro">
            These tools are built on the TPG Persuasive Storytelling methodology. Five frameworks.
            Used in training programs across 17 countries. Deckspert puts them in your hands
            between presentations.
          </p>
          <p className="public-intro public-intro-tight">
            If you have not been through the training, start with the free tools. Then book a
            conversation.
          </p>
          <div className="public-action-row public-action-row-centered">
            <a className="public-outline-button" href={methodologyUrl} target="_blank" rel="noopener noreferrer">
              Learn about the training programs
            </a>
          </div>
        </div>
      </section>

      {/* ── Results ───────────────────────────────────────────────────── */}
      <section className="public-section public-section-dark">
        <div className="public-section-inner">
          <p className="public-kicker">Results</p>
          <h2>Teams that present better close more.</h2>
          <div className="public-stat-row">
            {proofPoints.map((point) => (
              <div className="public-stat-card" key={point.value}>
                <strong>{point.value}</strong>
                <span>{point.label}</span>
              </div>
            ))}
          </div>
          <div className="public-quote-grid">
            {testimonials.map((item) => (
              <figure className="public-quote-card public-quote-card-dark" key={item.person}>
                <blockquote>{item.quote}</blockquote>
                <figcaption>
                  <strong>{item.person}</strong>
                  <span>{item.company}</span>
                  <em>Outcome from TPG storytelling training</em>
                </figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ─────────────────────────────────────────────────── */}
      <section className="public-section public-section-dark public-final-cta">
        <div className="public-section-inner public-centered-copy">
          <h2>Ready to get more yeses, more often?</h2>
          <p className="public-intro">
            Start with a free evaluation. Or book a conversation with Todd. Either way, you will
            see the difference.
          </p>
          <div className="public-action-row public-action-row-centered">
            <Link className="public-primary-button" to="/free-evaluator">
              Try the Free Evaluator
            </Link>
            <a
              className="public-outline-button public-outline-button-dark"
              href={CALENDLY}
              target="_blank"
              rel="noopener noreferrer"
            >
              Book a discovery call
            </a>
            <Link className="public-text-link-dark" to="/pricing">
              Explore pricing
            </Link>
          </div>
        </div>
      </section>

    </div>
  );
}
